### Creates a new entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "NeZau",
  "email": "test22@example.com",
  "address": "123 main street22",
  "dateOfBirth": "1999-12-31",
  "registeredDate": "2025-10-30"

}

###